-- pgturbohybrid 0.1.0 --> 0.1.1
--
-- 0.1.1 is a maintenance release. Its substance is in the C library (the
-- pgturbohybrid.so shared object) and the build/CI tooling, not in the SQL
-- catalog: correctness hardening (volatile across PG_TRY/PG_CATCH), a faster
-- exact-MaxSim kernel dispatch, additional binary-input test coverage,
-- dead-code removal, and keyless signing of release artifacts.
--
-- The exported SQL surface -- types, operators, opclasses, functions, and
-- their maturity COMMENTs -- is unchanged from 0.1.0, so this upgrade applies
-- no DDL. It exists so that the upgrade path is exercisable
-- (ALTER EXTENSION pgturbohybrid UPDATE) and so future migrations have a base
-- to chain from. See sql/pgturbohybrid--0.1.1.sql for the full 0.1.1 catalog
-- (identical to 0.1.0) and RELEASE.md for the versioning policy.
